version: 0.2
# Pre-builds, Log into the repository
# Build, Build, then tag the image
# Post-Build, push the ECR
phases:
    pre_build:
        commands:
            - echo Logging into ECR...
            - $(aws ecr get-login --region us-east-1)
    build:
        commands:
            - echo Successfully logged in, building docker image
            - docker build -t php-test .
            - echo Image built, tagging image
            - docker tag php-test:latest 466336452057.dkr.ecr.us-east-1.amazonaws.com/php-test:latest
    post_build:
        commands:
            - echo Image created and tagged, pushing to Container Registry...
            - docker push 466336452057.dkr.ecr.us-east-1.amazonaws.com/php-test:latest
