version: 0.2
# Pre-builds, Log into the repository
# Build, Build, then tag the image
# Post-Build, push the ECR
phases:
    pre_build:
        commands:
            - echo Logging into ECR...
            - $(aws ecr get-login --region us-east-1)
    build:
        commands:
            - echo Successfully logged in, building docker image
            - docker build -t ifs-support-portal .
            - echo Image built, tagging image
            - docker tag ifs-support-portal:latest 630232151802.dkr.ecr.us-east-1.amazonaws.com/ifs-support-portal:latest
    post_build:
        commands:
            - echo Image created and tagged, pushing to Container Registry...
            - docker push 630232151802.dkr.ecr.us-east-1.amazonaws.com/ifs-support-portal:latest
